[package]
name = "hhg-app"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["staticlib"]  

[dependencies]
hhg-traits = { path = "../hhg-traits" }
hhg-hardware = { path = "../hhg-hardware" }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"